# Setup

## DB

### 1. sqlite

In [7]:
# from langchain.chains import create_sql_query_chain
# from langchain_community.utilities import SQLDatabase

# db = SQLDatabase.from_uri("sqlite:///catastici.db")

# # test DB
# print(db.dialect)
# print(db.get_usable_table_names())
# db.run("SELECT * FROM catastici LIMIT 1;")

sqlite
['catastici']

"[('liberal', 'campi', 'casa e bottega da barbier', '70 ducati', 'campo vicino alla chiesa')]"

### 2. postgresql

In [4]:
# Establish a connection to the PostgreSQL database
import psycopg2
password='Jakh=J0hn0103'
host='128.179.210.75'
db='catastici'

conn = psycopg2.connect(
    host=host,
    port=5432,
    user='postgres',
    password=password,
    database=db
)

# Test the connection
cursor = conn.cursor()
cursor.execute("SELECT * FROM catastici LIMIT 1")
rows = cursor.fetchall()
for row in rows:
    print(row)
conn.close()

('liberal', 'campi', 'casa e bottega da barbier', 'campo vicino alla chiesa', '70 ducati')

In [5]:
from langchain_community.utilities import SQLDatabase

# Setup database
db = SQLDatabase.from_uri(f"postgresql+psycopg2://postgres:{password}@{host}:5432/{db}")

# test DB
print(db.dialect)
print(db.get_usable_table_names())
db.run("SELECT * FROM catastici LIMIT 1;")

postgresql
['catastici']

"[('liberal', 'campi', 'casa e bottega da barbier', 'campo vicino alla chiesa', '70 ducati')]"

## Executor

In [6]:
from langchain_community.tools.sql_database.tool import QuerySQLDataBaseTool

# SQL query executor
execute_query = QuerySQLDataBaseTool(db=db)
# test
execute_query.invoke({"query":'SELECT * FROM catastici LIMIT 1;'})

"[('liberal', 'campi', 'casa e bottega da barbier', 'campo vicino alla chiesa', '70 ducati')]"

## Dataset

In [32]:
import pandas as pd
questions = pd.read_csv('../data/test_db.csv')
questions

,level,category,question,answer
0,0,0,"What is the family name of ""chiara"" who owns ""...",stella
1,0,0,"What is the surname of ""alvise"" for the propri...",minoto
2,0,0,"What is the last name of ""zuanne"" who possesse...",loredan
3,0,0,"Can you tell me the family name of ""zuanne"" fo...",corao
4,0,0,Who is the owner's last name with the first na...,fini
5,0,1,"How much does ""zuane"" ""dona"" earn from their p...",35 ducati
6,0,1,"How much income does ""marc'antonio"" ""mocenigo""...",8 ducati
7,0,1,"What is the rental revenue collected by ""piero...",128 ducati
8,0,1,"What is the earnings of ""domenico"" ""giovanelli...",12 ducati
9,0,1,"What is the amount of ducats ""cristofolo"" ""ros...",40 ducati
10,0,2,"What type of property does ""fausto"" ""da pase"" ...",casa in soler
11,0,2,"What type of property does ""daniela"" ""morosini...",casa
12,0,2,"What category of real estate does ""anibal"" ""fo...",magazen
13,0,2,"What kind of property is owned by ""piero"" ""fos...","casa, vuota"
14,0,2,"What is the property classification owned by ""...",casa a pepiano
15,0,3,"Where is the property ""magazen da oglio"" of ""f...",corte tagliapietra
16,0,3,"Where is the ""casa"" owned by ""zacaria"" ""valier...",corte nova
17,0,3,"What is the location of ""alvise"" ""barbarigo""'s...",calle del isolotto sopra le scalle primo soler
18,0,3,Can you pinpoint the whereabouts of the proper...,calle di christi
19,0,3,"In which area is the property owned by ""marco""...",calle del spezier
20,0,4,"Who owns a property ""casetta"" in ""corte della ...",elisabetta palatina mora
21,0,4,"Who is the proprietor of a ""casetta a pepian"" ...",regina contini
22,0,4,"Who owns the property type ""casa"" in ""calle de...",bortolo alberegno
23,0,4,Can you identify the individual who possesses ...,polo renier ponte
24,0,4,What is the name of the owner with the family ...,zuanne sagredo
25,1,0,"How many properties are owned by ""michiel"" ""mo...",126
26,1,0,"How many properties does ""maria"" ""zane venier""...",9
27,1,0,"What is the count of properties owned by ""dome...",2
28,1,0,How many properties are under the ownership of...,6
29,1,0,What is the total number of properties owned b...,2
30,1,1,How many different property types are there in...,3231
31,1,1,How many distinct property types are present i...,3231
32,1,1,What is the count of unique property types in ...,3231
33,1,1,How many different categories of properties ex...,3231
34,1,1,What is the total number of distinct property ...,3231
35,1,2,How many unique owners are there in the dataset?,6012
36,1,2,How many unique owners are listed in the dataset?,6012
37,1,2,What is the count of distinct owners in the da...,6012
38,1,2,How many different owners are recorded in the ...,6012
39,1,2,What is the total number of individual owners ...,6012
40,1,3,"How many properties are located in ""corte del ...",7
41,1,3,"How many properties are situated in ""corte del...",1
42,1,3,"What is the count of properties located in ""co...",21
43,1,3,"How many properties exist within ""calle del vo...",29
44,1,3,What is the total number of properties found i...,23
45,1,4,How many properties are owned by owners with t...,1
46,1,4,How many properties are owned by individuals w...,74
47,1,4,What is the count of properties owned by those...,155
48,1,4,How many properties are in possession of indiv...,317
49,1,4,What is the total number of properties owned b...,119
50,1,5,How many properties are owned by owners with t...,14
51,1,5,How many properties are owned by individuals w...,98
52,1,5,What is the count of properties owned by indiv...,1
53,1,5,How many properties are registered under indiv...,203
54,1,5,What is the total number of properties held by...,126
55,1,6,"What properties does ""zuanne"" ""bragadin"" own a...","['calle del forno', 'in corte dei vechii vicin..."
56,1,6,"Where are the properties owned by ""anzola"" ""ac...",['riva del vin']
57,1,6,"Can you list the locations where ""simon"" ""cont...","['calle dei bianchi', 'cale di ka tron', 'call..."
58,1,6,"Which locations are properties owned by ""paolo...",['calle del spicier']
59,1,6,What are the locations of the properties owned...,"['fondamenta del bagatin', 'giù dal ponte baga..."

# Text-to-SQL

## SQLCoder

In [4]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
# download the model
model_name = "defog/sqlcoder-7b-2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    use_cache=True,
    torch_dtype=torch.float16,
    device_map="auto"
)

/home/saydalie/.conda/envs/myenv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/saydalie/.local/lib/python3.11/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Downloading shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 5197.40it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████| 3/3 [00:11<00:00,  3.86s/it]

In [5]:
prompt = """### Task
Generate a PostgreSQL query to answer [QUESTION]{question}[/QUESTION]

### Instructions
- If you cannot answer the question with the available database schema, return 'I do not know'.

### Database Schema
You are asked a question about the people of Venice in 1740, who own properties.
All the information about the owner and the properties are given in the dataset.
The query will run on this database whose schema is represented in this string:
CREATE TABLE catastici
(
    Owner_First_Name VARCHAR(30), -- First name of the owner of the property
    Owner_Family_Name VARCHAR(30), -- Family name of the owner of the property
    Property_Type TEXT, -- Type of the property (e.g. casa, magazen, etc.)
    Rent_Income TEXT, -- Rent price of the property. It can be either a price in ducats, or the name of other good that is paid in exchange.
    Property_Location TEXT -- Ancient toponym of the property
);

### Answer
Given the database schema, here is the PostgreSQL query that answers [QUESTION]{question}[/QUESTION]
[PostgreSQL]
"""

In [6]:
import sqlparse

model.to('cuda')
def generate_query(question):
    updated_prompt = prompt.format(question=question)
    inputs = tokenizer(updated_prompt, return_tensors="pt").to("cuda")
    generated_ids = model.generate(
        **inputs,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id,
        max_new_tokens=400,
        do_sample=False,
        num_beams=1,
    )
    outputs = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    return sqlparse.format(outputs[0].split("[PostgreSQL]")[-1], reindent=True)

In [13]:
query = '''What is the last name of "zuanne" who possesses "casa" at "calle de gobbi"?'''
generated_sql = generate_query(query)
print(generated_sql)

SELECT c.Owner_Family_Name
FROM catastici c
WHERE c.Owner_First_Name ilike '%zuanne%'
  AND c.Property_Type ilike '%casa%'
  AND c.Property_Location ilike '%calle de gobbi%'
ORDER BY c.Owner_Family_Name NULLS LAST
LIMIT 1

In [14]:
from pprint import pprint
pprint(execute_query.invoke({"query":generated_sql}))

"[('loredan',)]"

### Test on Dataset

In [15]:
generated_sqls = []
generated_answers = []

for i,r in questions.iterrows():
    generated_sql = generate_query(r['question'])
    generated_sqls.append(generated_sql)
    generated_answer = execute_query.invoke({"query":generated_sql})
    generated_answers.append(generated_answer)

In [16]:
questions['generated_sql'] = generated_sqls
questions['generated_answer'] = generated_answers

In [17]:
questions

,level,category,question,answer,generated_sql,generated_answer
0,0,0,"What is the family name of ""chiara"" who owns ""...",stella,\nSELECT c.Owner_Family_Name\nFROM catastici c...,
1,0,0,"What is the surname of ""alvise"" for the propri...",minoto,\nSELECT c.Owner_Family_Name\nFROM catastici c...,
2,0,0,"What is the last name of ""zuanne"" who possesse...",loredan,\nSELECT c.Owner_Family_Name\nFROM catastici c...,"[('loredan',)]"
3,0,0,"Can you tell me the family name of ""zuanne"" fo...",corao,\nSELECT c.Owner_Family_Name\nFROM catastici c...,"[('corao',)]"
4,0,0,Who is the owner's last name with the first na...,fini,\nSELECT c.Owner_Family_Name\nFROM catastici c...,
5,0,1,"How much does ""zuane"" ""dona"" earn from their p...",35 ducati,\nSELECT c.Rent_Income\nFROM catastici c\nWHER...,"[('35 ducati',)]"
6,0,1,"How much income does ""marc'antonio"" ""mocenigo""...",8 ducati,\nSELECT c.Rent_Income\nFROM catastici c\nWHER...,"[('8 ducati',)]"
7,0,1,"What is the rental revenue collected by ""piero...",128 ducati,\nSELECT c.Rent_Income\nFROM catastici c\nWHER...,
8,0,1,"What is the earnings of ""domenico"" ""giovanelli...",12 ducati,\nSELECT c.Rent_Income\nFROM catastici c\nWHER...,"[('12 ducati',), ('10 ducati',), ('14 ducati',..."
9,0,1,"What is the amount of ducats ""cristofolo"" ""ros...",40 ducati,\nSELECT SUM(c.Rent_Income::INTEGER) AS total_...,"[(None,)]"
10,0,2,"What type of property does ""fausto"" ""da pase"" ...",casa in soler,\nSELECT c.Property_Type\nFROM catastici c\nWH...,"[('casa in soler vuota',)]"
11,0,2,"What type of property does ""daniela"" ""morosini...",casa,\nSELECT c.Property_Type\nFROM catastici c\nWH...,"[('casa',)]"
12,0,2,"What category of real estate does ""anibal"" ""fo...",magazen,\nSELECT c.Property_Type\nFROM catastici c\nWH...,"[('casa pepian',), ('magazen',)]"
13,0,2,"What kind of property is owned by ""piero"" ""fos...","casa, vuota",\nSELECT c.Property_Type\nFROM catastici c\nWH...,"[('casa, vuota',)]"
14,0,2,"What is the property classification owned by ""...",casa a pepiano,\nSELECT c.Property_Type\nFROM catastici c\nWH...,"[('casa a pepiano',), ('casa a pepiano',), ('c..."
15,0,3,"Where is the property ""magazen da oglio"" of ""f...",corte tagliapietra,\nSELECT c.Property_Location\nFROM catastici c...,"[('corte tagliapietra',)]"
16,0,3,"Where is the ""casa"" owned by ""zacaria"" ""valier...",corte nova,\nSELECT c.Property_Location\nFROM catastici c...,"[('corte nova',), ('corte nova',), ('calle del..."
17,0,3,"What is the location of ""alvise"" ""barbarigo""'s...",calle del isolotto sopra le scalle primo soler,\nSELECT c.Property_Location\nFROM catastici c...,[('calle del isolotto sopra le scalle primo so...
18,0,3,Can you pinpoint the whereabouts of the proper...,calle di christi,\nSELECT c.Property_Location\nFROM catastici c...,"[('calle di christi',)]"
19,0,3,"In which area is the property owned by ""marco""...",calle del spezier,\nSELECT c.Property_Location\nFROM catastici c...,
20,0,4,"Who owns a property ""casetta"" in ""corte della ...",elisabetta palatina mora,"\nSELECT c.Owner_First_Name,\n c.Owner_F...","[('elisabetta palatina', 'mora'), ('gioseppe m..."
21,0,4,"Who is the proprietor of a ""casetta a pepian"" ...",regina contini,"\nSELECT c.Owner_First_Name,\n c.Owner_F...","[('regina', 'contini')]"
22,0,4,"Who owns the property type ""casa"" in ""calle de...",bortolo alberegno,"\nSELECT c.Owner_First_Name,\n c.Owner_F...","[('bortolo', 'alberegno'), ('bortolo', 'albere..."
23,0,4,Can you identify the individual who possesses ...,polo renier ponte,"\nSELECT c.Owner_First_Name,\n c.Owner_F...","[('polo', 'renier ponte')]"
24,0,4,What is the name of the owner with the family ...,zuanne sagredo,"\nSELECT c.Owner_First_Name,\n c.Owner_F...","[('zuanne', 'sagredo'), ('zuanne', 'sagredo'),..."
25,1,0,"How many properties are owned by ""michiel"" ""mo...",126,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(126,)]"
26,1,0,"How many properties does ""maria"" ""zane venier""...",9,\nSELECT COUNT(c.Property_Type) AS number_of_p...,"[(9,)]"
27,1,0,"What is the count of properties owned by ""dome...",2,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(2,)]"
28,1,0,How many properties are under the ownership of...,6,\nSELECT COUNT(c.Property_Type) AS number_of_p...,"[(12,)]"
29,1,0,What is the total number of properties owned b...,2,\nSELECT COUNT(c.Property_Type) AS total_prope...,"[(2,)]"
30,1,1,How many different property types are there in...,3231,\nSELECT COUNT(DISTINCT c.Property_Type)\nFROM...,"[(3231,)]"
31,1,1,How many distinct property types are present i...,3231,\nSELECT COUNT(DISTINCT c.Property_Type)\nFROM...,"[(3231,)]"
32,1,1,What is the count of unique property types in ...,3231,\nSELECT COUNT(DISTINCT c.Property_Type)\nFROM...,"[(3231,)]"
33,1,1,How many different categories of properties ex...,3231,\nSELECT COUNT(DISTINCT c.Property_Type)\nFROM...,"[(3231,)]"
34,1,1,What is the total number of distinct property ...,3231,\nSELECT COUNT(DISTINCT c.Property_Type)\nFROM...,"[(3231,)]"
35,1,2,How many unique owners are there in the dataset?,6012,"\nSELECT COUNT(DISTINCT c.Owner_First_Name, c....",Error: (psycopg2.errors.UndefinedFunction) fun...
36,1,2,How many unique owners are listed in the dataset?,6012,"\nSELECT COUNT(DISTINCT c.Owner_First_Name, c....",Error: (psycopg2.errors.UndefinedFunction) fun...
37,1,2,What is the count of distinct owners in the da...,6012,"\nSELECT COUNT(DISTINCT c.Owner_First_Name, c....",Error: (psycopg2.errors.UndefinedFunction) fun...
38,1,2,How many different owners are recorded in the ...,6012,"\nSELECT COUNT(DISTINCT c.Owner_First_Name, c....",Error: (psycopg2.errors.UndefinedFunction) fun...
39,1,2,What is the total number of individual owners ...,6012,"\nSELECT COUNT(DISTINCT c.Owner_First_Name, c....",Error: (psycopg2.errors.UndefinedFunction) fun...
40,1,3,"How many properties are located in ""corte del ...",7,\nSELECT COUNT(*)\nFROM catastici c\nWHERE c.P...,"[(7,)]"
41,1,3,"How many properties are situated in ""corte del...",1,\nSELECT COUNT(c.Property_Location)\nFROM cata...,"[(1,)]"
42,1,3,"What is the count of properties located in ""co...",21,\nSELECT COUNT(*)\nFROM catastici c\nWHERE c.P...,"[(22,)]"
43,1,3,"How many properties exist within ""calle del vo...",29,\nSELECT COUNT(c.Property_Location)\nFROM cata...,"[(49,)]"
44,1,3,What is the total number of properties found i...,23,\nSELECT 'I do not know' AS answer;,"[('I do not know',)]"
45,1,4,How many properties are owned by owners with t...,1,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(1,)]"
46,1,4,How many properties are owned by individuals w...,74,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(80,)]"
47,1,4,What is the count of properties owned by those...,155,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(157,)]"
48,1,4,How many properties are in possession of indiv...,317,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(345,)]"
49,1,4,What is the total number of properties owned b...,119,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(161,)]"
50,1,5,How many properties are owned by owners with t...,14,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(16,)]"
51,1,5,How many properties are owned by individuals w...,98,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(106,)]"
52,1,5,What is the count of properties owned by indiv...,1,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(1,)]"
53,1,5,How many properties are registered under indiv...,203,\nSELECT COUNT(c.Property_Type)\nFROM catastic...,"[(248,)]"
54,1,5,What is the total number of properties held by...,126,\nSELECT COUNT(c.Property_Type) AS total_prope...,"[(173,)]"
55,1,6,"What properties does ""zuanne"" ""bragadin"" own a...","['calle del forno', 'in corte dei vechii vicin...","\nSELECT c.Property_Type,\n c.Property_L...","[('casa in soler', 'calle del forno'), ('altro..."
56,1,6,"Where are the properties owned by ""anzola"" ""ac...",['riva del vin'],\nSELECT c.Property_Location\nFROM catastici c...,"[('riva del vin',), ('riva del vin',)]"
57,1,6,"Can you list the locations where ""simon"" ""cont...","['calle dei bianchi', 'cale di ka tron', 'call...",\nSELECT c.Property_Location\nFROM catastici c...,"[('calle del forno',), ('calle del forno',), (..."
58,1,6,"Which locations are properties owned by ""paolo...",['calle del spicier'],\nSELECT c.Property_Location\nFROM catastici c...,"[('calle del spicier',), ('calle del spicier',)]"
59,1,6,What are the locations of the properties owned...,"['fondamenta del bagatin', 'giù dal ponte baga...",\nSELECT c.Property_Location\nFROM catastici c...,"[('fondamenta del bagatin',), ('giù dal ponte ..."

### Evaluate

In [24]:
for _,row in questions.iterrows():
    print(row['category'])
    print(f"Question: {row['question']}")
    print(f"Answer: {row['answer']}")
    print(f"Query Result: {row['generated_answer']}")
    print('SQL:')
    print(row['generated_sql'])
    print('\n\n')

0
Question: What is the family name of "chiara" who owns "casa in 2 affittanze, porcion" in "corte nova"?
Answer: stella
Query Result:
SQL:

SELECT c.Owner_Family_Name
FROM catastici c
WHERE c.Owner_First_Name ilike '%chiara%'
  AND c.Property_Type ilike '%casa%'
  AND c.Property_Location ilike '%corte%nova%'
  AND c.Rent_Income ilike '%2%affittanze%porcion%';



0
Question: What is the surname of "alvise" for the proprietorship of "casa, per l'altra metà" at "in fondamenta appresso il ponte di ca' marcello"?
Answer: minoto
Query Result:
SQL:

SELECT c.Owner_Family_Name
FROM catastici c
WHERE c.Owner_First_Name ilike '%alvise%'
  AND c.Property_Type ilike '%casa%'
  AND c.Property_Location ilike '%in fondamenta appresso il ponte di ca''marcello%'



0
Question: What is the last name of "zuanne" who possesses "casa" at "calle de gobbi"?
Answer: loredan
Query Result: [('loredan',)]
SQL:

SELECT c.Owner_Family_Name
FROM catastici c
WHERE c.Owner_First_Name ilike '%zuanne%'
  AND c.Property_Type ilike '%casa%'
  AND c.Property_Location ilike '%calle de gobbi%'
ORDER BY c.Owner_Family_Name NULLS LAST
LIMIT 1



0
Question: Can you tell me the family name of "zuanne" for the ownership of "bottegha da fruttarol serve per proprio uso" situated in "calle larga"?
Answer: corao
Query Result: [('corao',)]
SQL:

SELECT c.Owner_Family_Name
FROM catastici c
WHERE c.Owner_First_Name ilike '%zuanne%'
  AND c.Property_Type ilike '%bottegha%da%fruttarol%serve%per%proprio%uso%'
  AND c.Property_Location ilike '%calle%larg%a%'



0
Question: Who is the owner's last name with the first name of "gerolamo" for the property type "casa" located at "calle di ca' boldù"?
Answer: fini
Query Result:
SQL:

SELECT c.Owner_Family_Name
FROM catastici c
WHERE c.Owner_First_Name ilike '%gerolamo%'
  AND c.Property_Type ilike '%casa%'
  AND c.Property_Location ilike '%calle di ca''boldù%'



1
Question: How much does "zuane" "dona" earn from their property "casa" in "calle del sonzonio"?
Answer: 35 ducati
Query Result: [('35 ducati',)]
SQL:

SELECT c.Rent_Income
FROM catastici c
WHERE c.Owner_First_Name ilike '%zuane%'
  AND c.Owner_Family_Name ilike '%dona%'
  AND c.Property_Type ilike '%casa%'
  AND c.Property_Location ilike '%calle%del%sonzonio%'



1
Question: How much income does "marc'antonio" "mocenigo" generate from the property labeled as "casa a pepian" in "calle de longhi"?
Answer: 8 ducati
Query Result: [('8 ducati',)]
SQL:

SELECT c.Rent_Income
FROM catastici c
WHERE c.Owner_First_Name ilike '%marc''antonio%'
  AND c.Owner_Family_Name ilike '%mocenigo%'
  AND c.Property_Type ilike '%casa%a%pepian%'
  AND c.Property_Location ilike '%calle%de%longhi%';



1
Question: What is the rental revenue collected by "piero" "giusti" from their "procuratia" in "seconda corte nella procuratia"?
Answer: 128 ducati
Query Result:
SQL:

SELECT c.Rent_Income
FROM catastici c
WHERE c.Owner_First_Name ilike '%piero%'
  AND c.Owner_Family_Name ilike '%giusti%'
  AND c.Property_Location ilike '%procuratia%seconda%corte%nella%procuratia%';



1
Question: What is the earnings of "domenico" "giovanelli" from their property type "casa a pepiano" located in "corte della vida"?
Answer: 12 ducati
Query Result: [('12 ducati',), ('10 ducati',), ('14 ducati',), ('14 ducati',), ('14 ducati',), ('14 ducati',)]
SQL:

SELECT c.Rent_Income
FROM catastici c
WHERE c.Owner_First_Name ilike '%domenico%'
  AND c.Owner_Family_Name ilike '%giovanelli%'
  AND c.Property_Type ilike '%casa a pepiano%'
  AND c.Property_Location ilike '%corte della vida%';



1
Question: What is the amount of ducats "cristofolo" "rossetti" makes annually from the "altro appartamento" in "calle dei botteri"?
Answer: 40 ducati
Query Result: [(None,)]
SQL:

SELECT SUM(c.Rent_Income::INTEGER) AS total_ducats
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%cristofolo%'
  AND c.Owner_Family_Name ILIKE '%rossetti%'
  AND c.Property_Type ILIKE '%casa%'
  AND c.Property_Location ILIKE '%calle%dei%botteri%'



2
Question: What type of property does "fausto" "da pase" own in "al ponticello della toletta"?
Answer: casa in soler
Query Result: [('casa in soler vuota',)]
SQL:

SELECT c.Property_Type
FROM catastici c
WHERE c.Owner_First_Name ilike '%fausto%'
  AND c.Owner_Family_Name ilike '%da pase%'
  AND c.Property_Location ilike '%al ponticello della toletta%'
LIMIT 1



2
Question: What type of property does "daniela" "morosini" possess at "calle del magazen vechio"?
Answer: casa
Query Result: [('casa',)]
SQL:

SELECT c.Property_Type
FROM catastici c
WHERE c.Owner_First_Name ilike '%daniela%'
  AND c.Owner_Family_Name ilike '%morosini%'
  AND c.Property_Location ilike '%calle%del%magazen%vechio%'
LIMIT 1



2
Question: What category of real estate does "anibal" "fonte" own in "corte stella"?
Answer: magazen
Query Result: [('casa pepian',), ('magazen',)]
SQL:

SELECT c.Property_Type
FROM catastici c
WHERE c.Owner_First_Name ilike '%anibal%'
  AND c.Owner_Family_Name ilike '%fonte%'
  AND c.Property_Location ilike '%corte%stella%'



2
Question: What kind of property is owned by "piero" "foscarini" at "sopra altra casa"?
Answer: casa, vuota
Query Result: [('casa, vuota',)]
SQL:

SELECT c.Property_Type
FROM catastici c
WHERE c.Owner_First_Name ilike '%piero%'
  AND c.Owner_Family_Name ilike '%foscarini%'
  AND c.Property_Location ilike '%sopra%altra%casa%'
LIMIT 1



2
Question: What is the property classification owned by "zuanne" "frascinetti" in "corte dell'anzolo"?
Answer: casa a pepiano
Query Result: [('casa a pepiano',), ('casa a pepiano',), ('casa in soler',)]
SQL:

SELECT c.Property_Type
FROM catastici c
WHERE c.Owner_First_Name ilike '%zuanne%'
  AND c.Owner_Family_Name ilike '%frascinetti%'
  AND c.Property_Location ilike '%corte dell''anzolo%'
ORDER BY c.Property_Type NULLS LAST;



3
Question: Where is the property "magazen da oglio" of "filippo" "pasqualigo" located?
Answer: corte tagliapietra
Query Result: [('corte tagliapietra',)]
SQL:

SELECT c.Property_Location
FROM catastici c
WHERE c.Owner_First_Name ilike '%filippo%'
  AND c.Owner_Family_Name ilike '%pasqualigo%'
  AND c.Property_Type ilike '%magazen%da%oglio%';



3
Question: Where is the "casa" owned by "zacaria" "valier" situated?
Answer: corte nova
Query Result: [('corte nova',), ('corte nova',), ('calle della vida',)]
SQL:

SELECT c.Property_Location
FROM catastici c
WHERE c.Owner_First_Name ilike '%zacaria%'
  AND c.Owner_Family_Name ilike '%valier%'
  AND c.Property_Type ilike '%casa%';



3
Question: What is the location of "alvise" "barbarigo"'s "volta una"?
Answer: calle del isolotto sopra le scalle primo soler
Query Result: [('calle del isolotto sopra le scalle primo soler',)]
SQL:

SELECT c.Property_Location
FROM catastici c
WHERE c.Owner_First_Name ilike '%alvise%'
  AND c.Owner_Family_Name ilike '%barbarigo%'
  AND c.Property_Type ilike '%volta%una%';



3
Question: Can you pinpoint the whereabouts of the property owned by "pietro" "grimani luca" with the type of "bottegha da fenestrer"?
Answer: calle di christi
Query Result: [('calle di christi',)]
SQL:

SELECT c.Property_Location
FROM catastici c
WHERE c.Owner_First_Name ilike '%pietro%'
  AND c.Owner_Family_Name ilike '%grimani%luca%'
  AND c.Property_Type ilike '%bottegha%da%fenestrer%'



3
Question: In which area is the property owned by "marco" "dariva" found, categorized as "not given"?
Answer: calle del spezier
Query Result:
SQL:

SELECT c.Property_Location
FROM catastici c
WHERE c.Owner_First_Name ilike '%marco%'
  AND c.Owner_Family_Name ilike '%dariva%'
  AND c.Property_Location ilike '%not%given%'



4
Question: Who owns a property "casetta" in "corte della malvasia" with the family name of "mora"?
Answer: elisabetta palatina mora
Query Result: [('elisabetta palatina', 'mora'), ('gioseppe maria', 'mora'), ('gioseppe maria', 'mora'), ('elisabetta palatina', 'mora')]
SQL:

SELECT c.Owner_First_Name,
       c.Owner_Family_Name
FROM catastici c
WHERE c.Property_Type = 'casetta'
  AND c.Property_Location = 'corte della malvasia'
  AND c.Owner_Family_Name = 'mora'



4
Question: Who is the proprietor of a "casetta a pepian" in "corte busella" with the family name "contini"?
Answer: regina contini
Query Result: [('regina', 'contini')]
SQL:

SELECT c.Owner_First_Name,
       c.Owner_Family_Name
FROM catastici c
WHERE c.Property_Type = 'casetta a pepian'
  AND c.Property_Location = 'corte busella'
  AND c.Owner_Family_Name = 'contini'



4
Question: Who owns the property type "casa" in "calle del zadio" and bears the surname "alberegno"?
Answer: bortolo alberegno
Query Result: [('bortolo', 'alberegno'), ('bortolo', 'alberegno'), ('bortolo', 'alberegno')]
SQL:

SELECT c.Owner_First_Name,
       c.Owner_Family_Name
FROM catastici c
WHERE c.Property_Type = 'casa'
  AND c.Property_Location = 'calle del zadio'
  AND c.Owner_Family_Name = 'alberegno'



4
Question: Can you identify the individual who possesses a property categorized as "casa in solari con bottega da casseler" in "salizada" with the last name "renier ponte"?
Answer: polo renier ponte
Query Result: [('polo', 'renier ponte')]
SQL:

SELECT c.Owner_First_Name,
       c.Owner_Family_Name
FROM catastici c
WHERE c.Property_Type ilike '%casa in solari con bottega da casseler%'
  AND c.Property_Location ilike '%salizada%'
  AND c.Owner_Family_Name ilike '%renier ponte%'



4
Question: What is the name of the owner with the family name "sagredo" for the property type "magazen" situated in "calle de favri"?
Answer: zuanne sagredo
Query Result: [('zuanne', 'sagredo'), ('zuanne', 'sagredo'), ('zuanne', 'sagredo')]
SQL:

SELECT c.Owner_First_Name,
       c.Owner_Family_Name
FROM catastici c
WHERE c.Owner_Family_Name ilike '%sagredo%'
  AND c.Property_Type ilike '%magazen%'
  AND c.Property_Location ilike '%calle%de%favri%'



0
Question: How many properties are owned by "michiel" "morosini"?
Answer: 126
Query Result: [(126,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%michiel%'
  AND c.Owner_Family_Name ILIKE '%morosini%';



0
Question: How many properties does "maria" "zane venier" own?
Answer: 9
Query Result: [(9,)]
SQL:

SELECT COUNT(c.Property_Type) AS number_of_properties
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%maria%'
  AND c.Owner_Family_Name ILIKE '%zane%venier%';



0
Question: What is the count of properties owned by "domenico" "aldi"?
Answer: 2
Query Result: [(2,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%domenico%'
  AND c.Owner_Family_Name ILIKE '%aldi%';



0
Question: How many properties are under the ownership of "pier alvise" "barbaro"?
Answer: 6
Query Result: [(12,)]
SQL:

SELECT COUNT(c.Property_Type) AS number_of_properties
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%pier%alvise%'
  AND c.Owner_Family_Name ILIKE '%barbaro%';



0
Question: What is the total number of properties owned by "fiama" "fiorelli"?
Answer: 2
Query Result: [(2,)]
SQL:

SELECT COUNT(c.Property_Type) AS total_properties
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%fiama%'
  AND c.Owner_Family_Name ILIKE '%fiorelli%';



1
Question: How many different property types are there in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT c.Property_Type)
FROM catastici c;



1
Question: How many distinct property types are present in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT c.Property_Type)
FROM catastici c;



1
Question: What is the count of unique property types in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT c.Property_Type)
FROM catastici c;



1
Question: How many different categories of properties exist in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT c.Property_Type)
FROM catastici c;



1
Question: What is the total number of distinct property types listed?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT c.Property_Type)
FROM catastici c;



2
Question: How many unique owners are there in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedFunction) function count(character varying, character varying) does not exist
LINE 2: SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Nam...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)
FROM catastici c;]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)
FROM catastici c;



2
Question: How many unique owners are listed in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedFunction) function count(character varying, character varying) does not exist
LINE 2: SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Nam...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)
FROM catastici c;]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)
FROM catastici c;



2
Question: What is the count of distinct owners in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedFunction) function count(character varying, character varying) does not exist
LINE 2: SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Nam...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)
FROM catastici c;]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)
FROM catastici c;



2
Question: How many different owners are recorded in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedFunction) function count(character varying, character varying) does not exist
LINE 2: SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Nam...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)
FROM catastici c;]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)
FROM catastici c;



2
Question: What is the total number of individual owners represented in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedFunction) function count(character varying, character varying) does not exist
LINE 2: SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Nam...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name) AS total_owners
FROM catastici c;]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name) AS total_owners
FROM catastici c;



3
Question: How many properties are located in "corte del caparozolo"?
Answer: 7
Query Result: [(7,)]
SQL:

SELECT COUNT(*)
FROM catastici c
WHERE c.Property_Location ilike '%corte del caparozolo%'



3
Question: How many properties are situated in "corte delle candelle e in terren alli gesouiti"?
Answer: 1
Query Result: [(1,)]
SQL:

SELECT COUNT(c.Property_Location)
FROM catastici c
WHERE c.Property_Location ilike '%corte delle candelle e in terren alli gesouiti%'



3
Question: What is the count of properties located in "corte del figher"?
Answer: 21
Query Result: [(22,)]
SQL:

SELECT COUNT(*)
FROM catastici c
WHERE c.Property_Location ilike '%corte del figher%';



3
Question: How many properties exist within "calle del volto"?
Answer: 29
Query Result: [(49,)]
SQL:

SELECT COUNT(c.Property_Location)
FROM catastici c
WHERE c.Property_Location ilike '%calle%del%volto%'



3
Question: What is the total number of properties found in "sopra la lista alla colonna"?
Answer: 23
Query Result: [('I do not know',)]
SQL:

SELECT 'I do not know' AS answer;



4
Question: How many properties are owned by owners with the first name "pier'alvise"?
Answer: 1
Query Result: [(1,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_First_Name ilike '%pier''alvise%';



4
Question: How many properties are owned by individuals with the first name "cecilia"?
Answer: 74
Query Result: [(80,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%cecilia%';



4
Question: What is the count of properties owned by those with the given name "carlo"?
Answer: 155
Query Result: [(157,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%carlo%';



4
Question: How many properties are in possession of individuals named "michiel"?
Answer: 317
Query Result: [(345,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%michiel%';



4
Question: What is the total number of properties owned by those with the first name "zuane"?
Answer: 119
Query Result: [(161,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%zuane%';



5
Question: How many properties are owned by owners with the last name "carli"?
Answer: 14
Query Result: [(16,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_Family_Name ILIKE '%carli%';



5
Question: How many properties are owned by individuals with the last name "nani"?
Answer: 98
Query Result: [(106,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_Family_Name ILIKE '%nani%';



5
Question: What is the count of properties owned by individuals with the surname "previani"?
Answer: 1
Query Result: [(1,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_Family_Name ILIKE '%previani%';



5
Question: How many properties are registered under individuals with the family name "loredan"?
Answer: 203
Query Result: [(248,)]
SQL:

SELECT COUNT(c.Property_Type)
FROM catastici c
WHERE c.Owner_Family_Name ILIKE '%loredan%';



5
Question: What is the total number of properties held by individuals sharing the last name "pasqualigo"?
Answer: 126
Query Result: [(173,)]
SQL:

SELECT COUNT(c.Property_Type) AS total_properties
FROM catastici c
WHERE c.Owner_Family_Name ILIKE '%pasqualigo%';



6
Question: What properties does "zuanne" "bragadin" own and where are they located?
Answer: ['calle del forno', 'in corte dei vechii vicin al campo', 'in campo in faccia della chiesa', 'in calle scaletta', 'calle dei frati', 'corte delle ancore', 'soler di sotto', 'calle del capitello']
Query Result: [('casa in soler', 'calle del forno'), ('altro appartamento', 'calle del forno'), ('altro appartamento', 'calle del forno'), ('casa a pepian', 'calle del forno'), ('casa in soler', 'calle del forno'), ('altro appartamento', 'calle del forno'), ('altro appartamento', 'calle del forno'), ('altro appartamento', 'calle del forno'), ('altro appartamento', 'calle del forno'), ('altro appartamento', 'calle del forno'), ('casa in soler', 'calle del forno'), ('casa', 'in corte dei vechii vicin al campo'), ('casa', 'in corte dei vechii vicin al campo'), ('casa di sua raggion e per suo uso', 'in campo in faccia della chiesa'), ('magazen', 'in calle scaletta'), ('magazen', 'in calle scaletta'), ('casa', 'calle dei frati'), ('magazen', 'corte delle ancore'), ('magazen', 'corte delle ancore'), ('volte numero 2', 'soler di sotto'), ('magazen', 'calle del capitello')]
SQL:

SELECT c.Property_Type,
       c.Property_Location
FROM catastici c
WHERE c.Owner_First_Name ILIKE '%zuanne%'
  AND c.Owner_Family_Name ILIKE '%bragadin%'



6
Question: Where are the properties owned by "anzola" "acquisti" situated?
Answer: ['riva del vin']

#### Wrong answers:
1. Specify the location, property type, by name explicitly. e.g. `property 'casa' that is located in '...'`, instead of `'casa' in '...'`
2. `ca' marcello` have been turned into `ca''marcello` -> whitespace missed when comes after `'`
3. Sometimes, running a query with `%` gives wrong answer as compared to without it: `WHERE c.Property_Location ilike '%corte del figher%'` instead of `WHERE c.Property_Location ilike 'corte del figher'`

#### Errors:
1. Multiple count: `COUNT(DISTINCT c.Owner_First_Name, c.Owner_Family_Name)`

_**True: 37**; Errors: 5; Wrong Answers: 18_

## CodeS

In [8]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = 'seeklhy/codes-7b'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name, 
    device_map = "auto", 
    torch_dtype = torch.float16
)
model.eval()

Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████| 3/3 [10:44<00:00, 214.75s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.24s/it]

GPTBigCodeForCausalLM(
  (transformer): GPTBigCodeModel(
    (wte): Embedding(49152, 4096)
    (wpe): Embedding(8192, 4096)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-41): 42 x GPTBigCodeBlock(
        (ln_1): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (attn): GPTBigCodeSdpaAttention(
          (c_attn): Linear(in_features=4096, out_features=4352, bias=True)
          (c_proj): Linear(in_features=4096, out_features=4096, bias=True)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (mlp): GPTBigCodeMLP(
          (c_fc): Linear(in_features=4096, out_features=16384, bias=True)
          (c_proj): Linear(in_features=16384, out_features=4096, bias=True)
          (act): GELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=4096, out_features=49152, bias=False)
)

In [9]:
prompt = """### Task
Generate a PostgreSQL query to answer [QUESTION]{question}[/QUESTION]

### Instructions
- If you cannot answer the question with the available database schema, return 'I do not know'.

### Database Schema
You are asked a question about the people of Venice in 1740, who own properties.
All the information about the owner and the properties are given in the dataset.
The query will run on this database whose schema is represented in this string:
CREATE TABLE catastici
(
    Owner_First_Name VARCHAR(30), -- First name of the owner of the property
    Owner_Family_Name VARCHAR(30), -- Family name of the owner of the property
    Property_Type TEXT, -- Type of the property (e.g. casa, magazen, etc.)
    Rent_Income TEXT, -- Rent price of the property. It can be either a price in ducats, or the name of other good that is paid in exchange.
    Property_Location TEXT -- Ancient toponym of the property
);

### Answer
Given the database schema, here is the PostgreSQL query that answers [QUESTION]{question}[/QUESTION]
[PostgreSQL]
"""

In [69]:
import sqlparse

def generate_queries(question, prompt=prompt, model=model, tokenizer=tokenizer, max_new_tokens=400, num_beams=1): # -> List
    updated_prompt = prompt.format(question=question)
    inputs = tokenizer(updated_prompt, return_tensors="pt").to("cuda")
    
    with torch.no_grad():
        generate_ids = model.generate(
            **inputs,
            max_new_tokens = max_new_tokens,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
            num_beams = num_beams,
            num_return_sequences = num_beams
        )
    outputs = tokenizer.batch_decode(generate_ids, skip_special_tokens = True, clean_up_tokenization_spaces = False)
    generated_sqls = [sqlparse.format(output.split("[PostgreSQL]")[-1].split(';')[0], reindent=True) for output in outputs]
    return generated_sqls

In [76]:
questions.iloc[1]['question']

'What is the surname of "alvise" for the proprietorship of "casa, per l\'altra metà" at "in fondamenta appresso il ponte di ca\' marcello"?'

In [77]:
query = '''What is the surname of "alvise" for the proprietorship of "casa, per l\'altra metà" at "in fondamenta appresso il ponte di ca\' marcello"?'''
generated_sqls = generate_queries(question=query)
[print(generated_sql, end='\n\n') for generated_sql in generated_sqls];

SELECT Owner_Family_Name
FROM catastici
WHERE Owner_First_Name = 'alvise'
  AND Property_Type = 'casa, per l''altra metà'
  AND Property_Location = 'in fondamenta appresso il ponte di ca'' marcello'

In [78]:
from pprint import pprint
for generated_sql in generated_sqls:
    pprint(execute_query.invoke({"query":generated_sql}))
    print()

"[('minoto',)]"

### Test on Dataset

In [79]:
generated_sqls = []
generated_answers = []

for i,r in questions.iterrows():
    generated_sql = generate_queries(r['question'])[0]
    generated_sqls.append(generated_sql)
    generated_answer = execute_query.invoke({"query":generated_sql})
    generated_answers.append(generated_answer)

In [80]:
questions['generated_sql'] = generated_sqls
questions['generated_answer'] = generated_answers

In [81]:
questions

,level,category,question,answer,generated_sql,generated_answer
0,0,0,"What is the family name of ""chiara"" who owns ""...",stella,Owner_Family_Name --------------------\nchiara...,Error: (psycopg2.errors.SyntaxError) syntax er...
1,0,0,"What is the surname of ""alvise"" for the propri...",minoto,\nSELECT Owner_Family_Name\nFROM catastici\nWH...,"[('minoto',)]"
2,0,0,"What is the last name of ""zuanne"" who possesse...",loredan,\nSELECT Owner_Family_Name\nFROM catastici\nWH...,"[('loredan',), ('loredan',), ('loredan',), ('l..."
3,0,0,"Can you tell me the family name of ""zuanne"" fo...",corao,\nSELECT Owner_Family_Name\nFROM catastici\nWH...,"[('corao',)]"
4,0,0,Who is the owner's last name with the first na...,fini,\nSELECT Owner_Family_Name\nFROM catastici\nWH...,"[('fini',)]"
5,0,1,"How much does ""zuane"" ""dona"" earn from their p...",35 ducati,\nSELECT SUM(Rent_Income)\nFROM catastici\nWHE...,Error: (psycopg2.errors.UndefinedFunction) fun...
6,0,1,"How much income does ""marc'antonio"" ""mocenigo""...",8 ducati,\nSELECT SUM(Rent_Income)\nFROM catastici\nWHE...,Error: (psycopg2.errors.UndefinedFunction) fun...
7,0,1,"What is the rental revenue collected by ""piero...",128 ducati,\nSELECT SUM(Rent_Income)\nFROM catastici\nWHE...,Error: (psycopg2.errors.UndefinedFunction) fun...
8,0,1,"What is the earnings of ""domenico"" ""giovanelli...",12 ducati,\nSELECT Rent_Income\nFROM catastici\nWHERE Ow...,"[('12 ducati',), ('10 ducati',), ('14 ducati',..."
9,0,1,"What is the amount of ducats ""cristofolo"" ""ros...",40 ducati,\nSELECT SUM(Rent_Income)\nFROM catastici\nWHE...,Error: (psycopg2.errors.UndefinedFunction) fun...
10,0,2,"What type of property does ""fausto"" ""da pase"" ...",casa in soler,\nSELECT Rent_Income\nFROM catastici\nWHERE Ow...,"[('28 ducati',), ('30 ducati',)]"
11,0,2,"What type of property does ""daniela"" ""morosini...",casa,\nSELECT Property_Type\nFROM catastici\nWHERE ...,"[('casa',)]"
12,0,2,"What category of real estate does ""anibal"" ""fo...",magazen,\nSELECT Property_Type\nFROM catastici\nWHERE ...,"[('casa pepian',), ('magazen',)]"
13,0,2,"What kind of property is owned by ""piero"" ""fos...","casa, vuota",\nSELECT AVG(Rent_Income)\nFROM catastici,Error: (psycopg2.errors.UndefinedFunction) fun...
14,0,2,"What is the property classification owned by ""...",casa a pepiano,\nSELECT Property_Type\nFROM catastici\nWHERE ...,"[('casa in soler',), ('casa a pepiano',), ('ca..."
15,0,3,"Where is the property ""magazen da oglio"" of ""f...",corte tagliapietra,\nSELECT Property_Location\nFROM catastici\nWH...,"[('corte tagliapietra',)]"
16,0,3,"Where is the ""casa"" owned by ""zacaria"" ""valier...",corte nova,\nSELECT Property_Location\nFROM catastici\nWH...,"[('corte nova',), ('corte nova',)]"
17,0,3,"What is the location of ""alvise"" ""barbarigo""'s...",calle del isolotto sopra le scalle primo soler,\nSELECT Property_Location\nFROM catastici\nWH...,[('calle del isolotto sopra le scalle primo so...
18,0,3,Can you pinpoint the whereabouts of the proper...,calle di christi,\nSELECT *\nFROM catastici\nWHERE Owner_First_...,"[('pietro', 'grimani luca', 'bottegha da fenes..."
19,0,3,"In which area is the property owned by ""marco""...",calle del spezier,\nSELECT Property_Location\nFROM catastici\nWH...,"[('calle del spezier',), ('calle del spezier',)]"
20,0,4,"Who owns a property ""casetta"" in ""corte della ...",elisabetta palatina mora,"\nSELECT Owner_First_Name,\n Owner_Famil...","[('elisabetta palatina', 'mora'), ('gioseppe m..."
21,0,4,"Who is the proprietor of a ""casetta a pepian"" ...",regina contini,"\nSELECT Owner_First_Name,\n Owner_Famil...","[('regina', 'contini')]"
22,0,4,"Who owns the property type ""casa"" in ""calle de...",bortolo alberegno,"\nSELECT Owner_First_Name,\n Owner_Famil...","[('bortolo', 'alberegno'), ('bortolo', 'albere..."
23,0,4,Can you identify the individual who possesses ...,polo renier ponte,"\nSELECT DISTINCT Owner_First_Name,\n ...","[('polo', 'renier ponte')]"
24,0,4,What is the name of the owner with the family ...,zuanne sagredo,"\nSELECT Owner_First_Name,\n Owner_Famil...","[('zuanne', 'sagredo')]"
25,1,0,"How many properties are owned by ""michiel"" ""mo...",126,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(126,)]"
26,1,0,"How many properties does ""maria"" ""zane venier""...",9,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(9,)]"
27,1,0,"What is the count of properties owned by ""dome...",2,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(2,)]"
28,1,0,How many properties are under the ownership of...,6,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(0,)]"
29,1,0,What is the total number of properties owned b...,2,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(2,)]"
30,1,1,How many different property types are there in...,3231,\nSELECT COUNT(DISTINCT Property_Type)\nFROM c...,"[(3231,)]"
31,1,1,How many distinct property types are present i...,3231,\nSELECT COUNT(DISTINCT Property_Type)\nFROM c...,"[(3231,)]"
32,1,1,What is the count of unique property types in ...,3231,\nSELECT COUNT(DISTINCT Property_Type)\nFROM c...,"[(3231,)]"
33,1,1,How many different categories of properties ex...,3231,\nSELECT COUNT(DISTINCT Property_Type)\nFROM c...,"[(3231,)]"
34,1,1,What is the total number of distinct property ...,3231,\nSELECT COUNT(DISTINCT Property_Type)\nFROM c...,"[(3231,)]"
35,1,2,How many unique owners are there in the dataset?,6012,"\nSELECT COUNT(DISTINCT Owner_First_Name) AS ""...","[(919,)]"
36,1,2,How many unique owners are listed in the dataset?,6012,"\nSELECT COUNT(DISTINCT Owner_First_Name) AS ""...","[(919,)]"
37,1,2,What is the count of distinct owners in the da...,6012,\nSELECT COUNT(DISTINCT Owner_First_Name)\nFRO...,"[(919,)]"
38,1,2,How many different owners are recorded in the ...,6012,"\nSELECT COUNT(DISTINCT Owner_First_Name) AS ""...","[(919,)]"
39,1,2,What is the total number of individual owners ...,6012,"\nSELECT COUNT(DISTINCT Owner_First_Name) AS ""...","[(919,)]"
40,1,3,"How many properties are located in ""corte del ...",7,\nSELECT COUNT(*)\nFROM catastici\nWHERE Prope...,"[(7,)]"
41,1,3,"How many properties are situated in ""corte del...",1,"\nSELECT Owner_First_Name,\n Owner_Famil...","[('nicolo', 'duodo', '26 casette incirca che p..."
42,1,3,"What is the count of properties located in ""co...",21,\nSELECT COUNT(*)\nFROM catastici\nWHERE Prope...,"[(21,)]"
43,1,3,"How many properties exist within ""calle del vo...",29,\nSELECT COUNT(*)\nFROM catastici\nWHERE Prope...,"[(29,)]"
44,1,3,What is the total number of properties found i...,23,\nSELECT COUNT(*)\nFROM catastici\nWHERE Prope...,"[(23,)]"
45,1,4,How many properties are owned by owners with t...,1,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(1,)]"
46,1,4,How many properties are owned by individuals w...,74,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(74,)]"
47,1,4,What is the count of properties owned by those...,155,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(0,)]"
48,1,4,How many properties are in possession of indiv...,317,\nSELECT AVG(Rent_Income)\nFROM catastici\nWHE...,Error: (psycopg2.errors.UndefinedFunction) fun...
49,1,4,What is the total number of properties owned b...,119,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(119,)]"
50,1,5,How many properties are owned by owners with t...,14,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(14,)]"
51,1,5,How many properties are owned by individuals w...,98,\nSELECT AVG(Rent_Income)\nFROM catastici\nWHE...,Error: (psycopg2.errors.UndefinedFunction) fun...
52,1,5,What is the count of properties owned by indiv...,1,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(1,)]"
53,1,5,How many properties are registered under indiv...,203,\nSELECT AVG(Rent_Income)\nFROM catastici\nWHE...,Error: (psycopg2.errors.UndefinedFunction) fun...
54,1,5,What is the total number of properties held by...,126,\nSELECT COUNT(*)\nFROM catastici\nWHERE Owner...,"[(126,)]"
55,1,6,"What properties does ""zuanne"" ""bragadin"" own a...","['calle del forno', 'in corte dei vechii vicin...","\nSELECT Owner_First_Name,\n Owner_Famil...","[('zuanne', 'bragadin', 'casa in soler', '8 du..."
56,1,6,"Where are the properties owned by ""anzola"" ""ac...",['riva del vin'],\nSELECT Property_Location\nFROM catastici\nWH...,"[('riva del vin',), ('riva del vin',)]"
57,1,6,"Can you list the locations where ""simon"" ""cont...","['calle dei bianchi', 'cale di ka tron', 'call...",\nSELECT DISTINCT Property_Location\nFROM cata...,"[('cale di ka tron',), ('calle dei bianchi',),..."
58,1,6,"Which locations are properties owned by ""paolo...",['calle del spicier'],\nSELECT DISTINCT Property_Location\nFROM cata...,"[('calle del spicier',)]"
59,1,6,What are the locations of the properties owned...,"['fondamenta del bagatin', 'giù dal ponte baga...",\nSELECT Property_Location\nFROM catastici\nWH...,"[('fondamenta del bagatin',), ('giù dal ponte ..."

### Evaluate

In [82]:
for _,row in questions.iterrows():
    print(row['category'])
    print(f"Question: {row['question']}")
    print(f"Answer: {row['answer']}")
    print(f"Query Result: {row['generated_answer']}")
    print('SQL:')
    print(row['generated_sql'])
    print('\n\n')

0
Question: What is the family name of "chiara" who owns "casa in 2 affittanze, porcion" in "corte nova"?
Answer: stella
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "Owner_Family_Name"
LINE 1: Owner_Family_Name --------------------
        ^

[SQL: Owner_Family_Name --------------------
chiara [/PostgreSQL] ### Note The query is case-sensitive,
                                                so the family name of the owner is "chiara"
and not "Chiara". The query is case-insensitive,
                                    so the property type is "casa"
and not "Casa". The query is case-insensitive,
                                  so the rent income is "2 affittanze, porcion"
and not "2 affittanze, Porcion". The query is case-insensitive,
                                                   so the property location is "corte nova"
and not "Corte Nova". The query is case-insensitive,
                                        so the owner's first name is "chiara" and not "Chiara".

The query is case-insensitive, so the owner's family name is "chiara"
and not "Chiara". The query is case-insensitive,
                                    so the property type is "casa"
and not "Casa". The query is case-insensitive,
                                  so the rent income is "2 affittanze, porcion"
and not "2 affitt]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
Owner_Family_Name --------------------
chiara [/PostgreSQL] ### Note The query is case-sensitive,
                                                so the family name of the owner is "chiara"
and not "Chiara". The query is case-insensitive,
                                    so the property type is "casa"
and not "Casa". The query is case-insensitive,
                                  so the rent income is "2 affittanze, porcion"
and not "2 affittanze, Porcion". The query is case-insensitive,
                                                   so the property location is "corte nova"
and not "Corte Nova". The query is case-insensitive,
                                        so the owner's first name is "chiara" and not "Chiara".

The query is case-insensitive, so the owner's family name is "chiara"
and not "Chiara". The query is case-insensitive,
                                    so the property type is "casa"
and not "Casa". The query is case-insensitive,
                                  so the rent income is "2 affittanze, porcion"
and not "2 affitt



0
Question: What is the surname of "alvise" for the proprietorship of "casa, per l'altra metà" at "in fondamenta appresso il ponte di ca' marcello"?
Answer: minoto
Query Result: [('minoto',)]
SQL:

SELECT Owner_Family_Name
FROM catastici
WHERE Owner_First_Name = 'alvise'
  AND Property_Type = 'casa, per l''altra metà'
  AND Property_Location = 'in fondamenta appresso il ponte di ca'' marcello'



0
Question: What is the last name of "zuanne" who possesses "casa" at "calle de gobbi"?
Answer: loredan
Query Result: [('loredan',), ('loredan',), ('loredan',), ('loredan',), ('loredan',)]
SQL:

SELECT Owner_Family_Name
FROM catastici
WHERE Owner_First_Name = 'zuanne'
  AND Property_Type = 'casa'
  AND Property_Location = 'calle de gobbi'



0
Question: Can you tell me the family name of "zuanne" for the ownership of "bottegha da fruttarol serve per proprio uso" situated in "calle larga"?
Answer: corao
Query Result: [('corao',)]
SQL:

SELECT Owner_Family_Name
FROM catastici
WHERE Owner_First_Name = 'zuanne'
  AND Property_Location = 'calle larga'
  AND Property_Type = 'bottegha da fruttarol serve per proprio uso'



0
Question: Who is the owner's last name with the first name of "gerolamo" for the property type "casa" located at "calle di ca' boldù"?
Answer: fini
Query Result: [('fini',)]
SQL:

SELECT Owner_Family_Name
FROM catastici
WHERE Owner_First_Name = 'gerolamo'
  AND Property_Type = 'casa'
  AND Property_Location = 'calle di ca'' boldù'



1
Question: How much does "zuane" "dona" earn from their property "casa" in "calle del sonzonio"?
Answer: 35 ducati
Query Result: Error: (psycopg2.errors.UndefinedFunction) function sum(text) does not exist
LINE 2: SELECT SUM(Rent_Income)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT SUM(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'zuane'
  AND Owner_Family_Name = 'dona'
  AND Property_Type = 'casa'
  AND Property_Location = 'calle del sonzonio']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT SUM(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'zuane'
  AND Owner_Family_Name = 'dona'
  AND Property_Type = 'casa'
  AND Property_Location = 'calle del sonzonio'



1
Question: How much income does "marc'antonio" "mocenigo" generate from the property labeled as "casa a pepian" in "calle de longhi"?
Answer: 8 ducati
Query Result: Error: (psycopg2.errors.UndefinedFunction) function sum(text) does not exist
LINE 2: SELECT SUM(Rent_Income)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT SUM(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'marc'
  AND Owner_Family_Name = 'mocenigo'
  AND Property_Type = 'casa a pepian'
  AND Property_Location = 'calle de longhi']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT SUM(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'marc'
  AND Owner_Family_Name = 'mocenigo'
  AND Property_Type = 'casa a pepian'
  AND Property_Location = 'calle de longhi'



1
Question: What is the rental revenue collected by "piero" "giusti" from their "procuratia" in "seconda corte nella procuratia"?
Answer: 128 ducati
Query Result: Error: (psycopg2.errors.UndefinedFunction) function sum(text) does not exist
LINE 2: SELECT SUM(Rent_Income)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT SUM(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'piero'
  AND Owner_Family_Name = 'giusti'
  AND Property_Location = 'seconda corte nella procuratia']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT SUM(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'piero'
  AND Owner_Family_Name = 'giusti'
  AND Property_Location = 'seconda corte nella procuratia'



1
Question: What is the earnings of "domenico" "giovanelli" from their property type "casa a pepiano" located in "corte della vida"?
Answer: 12 ducati
Query Result: [('12 ducati',), ('10 ducati',), ('14 ducati',), ('14 ducati',), ('14 ducati',), ('14 ducati',)]
SQL:

SELECT Rent_Income
FROM catastici
WHERE Owner_First_Name = 'domenico'
  AND Owner_Family_Name = 'giovanelli'
  AND Property_Type = 'casa a pepiano'
  AND Property_Location = 'corte della vida'



1
Question: What is the amount of ducats "cristofolo" "rossetti" makes annually from the "altro appartamento" in "calle dei botteri"?
Answer: 40 ducati
Query Result: Error: (psycopg2.errors.UndefinedFunction) function sum(text) does not exist
LINE 2: SELECT SUM(Rent_Income)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT SUM(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'cristofolo'
  AND Owner_Family_Name = 'rossetti'
  AND Property_Location = 'altro appartamento'
  AND Property_Type = 'appartamento']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT SUM(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'cristofolo'
  AND Owner_Family_Name = 'rossetti'
  AND Property_Location = 'altro appartamento'
  AND Property_Type = 'appartamento'



2
Question: What type of property does "fausto" "da pase" own in "al ponticello della toletta"?
Answer: casa in soler
Query Result: [('28 ducati',), ('30 ducati',)]
SQL:

SELECT Rent_Income
FROM catastici
WHERE Owner_First_Name = 'fausto'
  AND Owner_Family_Name = 'da pase'
  AND Property_Location = 'al ponticello della toletta'



2
Question: What type of property does "daniela" "morosini" possess at "calle del magazen vechio"?
Answer: casa
Query Result: [('casa',)]
SQL:

SELECT Property_Type
FROM catastici
WHERE Owner_First_Name = 'daniela'
  AND Owner_Family_Name = 'morosini'
  AND Property_Location = 'calle del magazen vechio'



2
Question: What category of real estate does "anibal" "fonte" own in "corte stella"?
Answer: magazen
Query Result: [('casa pepian',), ('magazen',)]
SQL:

SELECT Property_Type
FROM catastici
WHERE Owner_First_Name = 'anibal'
  AND Owner_Family_Name = 'fonte'
  AND Property_Location = 'corte stella'



2
Question: What kind of property is owned by "piero" "foscarini" at "sopra altra casa"?
Answer: casa, vuota
Query Result: Error: (psycopg2.errors.UndefinedFunction) function avg(text) does not exist
LINE 2: SELECT AVG(Rent_Income)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT AVG(Rent_Income)
FROM catastici]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT AVG(Rent_Income)
FROM catastici



2
Question: What is the property classification owned by "zuanne" "frascinetti" in "corte dell'anzolo"?
Answer: casa a pepiano
Query Result: [('casa in soler',), ('casa a pepiano',), ('casa a pepiano',)]
SQL:

SELECT Property_Type
FROM catastici
WHERE Owner_First_Name = 'zuanne'
  AND Owner_Family_Name = 'frascinetti'
  AND Property_Location = 'corte dell''anzolo'



3
Question: Where is the property "magazen da oglio" of "filippo" "pasqualigo" located?
Answer: corte tagliapietra
Query Result: [('corte tagliapietra',)]
SQL:

SELECT Property_Location
FROM catastici
WHERE Owner_First_Name = 'filippo'
  AND Owner_Family_Name = 'pasqualigo'
  AND Property_Type = 'magazen da oglio'



3
Question: Where is the "casa" owned by "zacaria" "valier" situated?
Answer: corte nova
Query Result: [('corte nova',), ('corte nova',)]
SQL:

SELECT Property_Location
FROM catastici
WHERE Owner_First_Name = 'zacaria'
  AND Owner_Family_Name = 'valier'
  AND Property_Type = 'casa'



3
Question: What is the location of "alvise" "barbarigo"'s "volta una"?
Answer: calle del isolotto sopra le scalle primo soler
Query Result: [('calle del isolotto sopra le scalle primo soler',)]
SQL:

SELECT Property_Location
FROM catastici
WHERE Owner_First_Name = 'alvise'
  AND Owner_Family_Name = 'barbarigo'
  AND Property_Type = 'volta una'



3
Question: Can you pinpoint the whereabouts of the property owned by "pietro" "grimani luca" with the type of "bottegha da fenestrer"?
Answer: calle di christi
Query Result: [('pietro', 'grimani luca', 'bottegha da fenestrer', 'calle di christi', '14 ducati')]
SQL:

SELECT *
FROM catastici
WHERE Owner_First_Name = 'pietro'
  AND Owner_Family_Name = 'grimani luca'
  AND Property_Type = 'bottegha da fenestrer'



3
Question: In which area is the property owned by "marco" "dariva" found, categorized as "not given"?
Answer: calle del spezier
Query Result: [('calle del spezier',), ('calle del spezier',)]
SQL:

SELECT Property_Location
FROM catastici
WHERE Owner_First_Name = 'marco'
  AND Owner_Family_Name = 'dariva'
  AND Property_Type = 'not given'



4
Question: Who owns a property "casetta" in "corte della malvasia" with the family name of "mora"?
Answer: elisabetta palatina mora
Query Result: [('elisabetta palatina', 'mora'), ('gioseppe maria', 'mora'), ('gioseppe maria', 'mora'), ('elisabetta palatina', 'mora')]
SQL:

SELECT Owner_First_Name,
       Owner_Family_Name
FROM catastici
WHERE Property_Type = 'casetta'
  AND Property_Location = 'corte della malvasia'
  AND Owner_Family_Name = 'mora'



4
Question: Who is the proprietor of a "casetta a pepian" in "corte busella" with the family name "contini"?
Answer: regina contini
Query Result: [('regina', 'contini')]
SQL:

SELECT Owner_First_Name,
       Owner_Family_Name
FROM catastici
WHERE Property_Type = 'casetta a pepian'
  AND Property_Location = 'corte busella'
  AND Owner_Family_Name = 'contini'



4
Question: Who owns the property type "casa" in "calle del zadio" and bears the surname "alberegno"?
Answer: bortolo alberegno
Query Result: [('bortolo', 'alberegno'), ('bortolo', 'alberegno'), ('bortolo', 'alberegno')]
SQL:

SELECT Owner_First_Name,
       Owner_Family_Name
FROM catastici
WHERE Property_Type = 'casa'
  AND Property_Location = 'calle del zadio'
  AND Owner_Family_Name = 'alberegno'



4
Question: Can you identify the individual who possesses a property categorized as "casa in solari con bottega da casseler" in "salizada" with the last name "renier ponte"?
Answer: polo renier ponte
Query Result: [('polo', 'renier ponte')]
SQL:

SELECT DISTINCT Owner_First_Name,
                Owner_Family_Name
FROM catastici
WHERE Property_Type = 'casa in solari con bottega da casseler'
  AND Property_Location = 'salizada'
  AND Owner_Family_Name = 'renier ponte'



4
Question: What is the name of the owner with the family name "sagredo" for the property type "magazen" situated in "calle de favri"?
Answer: zuanne sagredo
Query Result: [('zuanne', 'sagredo')]
SQL:

SELECT Owner_First_Name,
       Owner_Family_Name
FROM catastici
WHERE Owner_Family_Name = 'sagredo'
  AND Property_Type = 'magazen'
  AND Property_Location = 'calle de favri'



0
Question: How many properties are owned by "michiel" "morosini"?
Answer: 126
Query Result: [(126,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'michiel'
  AND Owner_Family_Name = 'morosini'



0
Question: How many properties does "maria" "zane venier" own?
Answer: 9
Query Result: [(9,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'maria'
  AND Owner_Family_Name = 'zane venier'



0
Question: What is the count of properties owned by "domenico" "aldi"?
Answer: 2
Query Result: [(2,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'domenico'
  AND Owner_Family_Name = 'aldi'



0
Question: How many properties are under the ownership of "pier alvise" "barbaro"?
Answer: 6
Query Result: [(0,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'pier'
  AND Owner_Family_Name = 'alvise'



0
Question: What is the total number of properties owned by "fiama" "fiorelli"?
Answer: 2
Query Result: [(2,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'fiama'
  AND Owner_Family_Name = 'fiorelli'



1
Question: How many different property types are there in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT Property_Type)
FROM catastici



1
Question: How many distinct property types are present in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT Property_Type)
FROM catastici



1
Question: What is the count of unique property types in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT Property_Type)
FROM catastici



1
Question: How many different categories of properties exist in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT Property_Type)
FROM catastici



1
Question: What is the total number of distinct property types listed?
Answer: 3231
Query Result: [(3231,)]
SQL:

SELECT COUNT(DISTINCT Property_Type)
FROM catastici



2
Question: How many unique owners are there in the dataset?
Answer: 6012
Query Result: [(919,)]
SQL:

SELECT COUNT(DISTINCT Owner_First_Name) AS "Number of unique owners"
FROM catastici



2
Question: How many unique owners are listed in the dataset?
Answer: 6012
Query Result: [(919,)]
SQL:

SELECT COUNT(DISTINCT Owner_First_Name) AS "Number of unique owners"
FROM catastici



2
Question: What is the count of distinct owners in the dataset?
Answer: 6012
Query Result: [(919,)]
SQL:

SELECT COUNT(DISTINCT Owner_First_Name)
FROM catastici



2
Question: How many different owners are recorded in the dataset?
Answer: 6012
Query Result: [(919,)]
SQL:

SELECT COUNT(DISTINCT Owner_First_Name) AS "Number of different owners"
FROM catastici



2
Question: What is the total number of individual owners represented in the dataset?
Answer: 6012
Query Result: [(919,)]
SQL:

SELECT COUNT(DISTINCT Owner_First_Name) AS "Total number of individual owners"
FROM catastici



3
Question: How many properties are located in "corte del caparozolo"?
Answer: 7
Query Result: [(7,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Property_Location = 'corte del caparozolo'



3
Question: How many properties are situated in "corte delle candelle e in terren alli gesouiti"?
Answer: 1
Query Result: [('nicolo', 'duodo', '26 casette incirca che per esser la maggior parte di tavole e in pessimo stato sono affittate a povere persone dalle quale ne ricava ciò che può', '0 ducati', 'corte delle candelle e in terren alli gesouiti')]
SQL:

SELECT Owner_First_Name,
       Owner_Family_Name,
       Property_Type,
       Rent_Income,
       Property_Location
FROM catastici
WHERE Property_Location = 'corte delle candelle e in terren alli gesouiti'



3
Question: What is the count of properties located in "corte del figher"?
Answer: 21
Query Result: [(21,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Property_Location = 'corte del figher'



3
Question: How many properties exist within "calle del volto"?
Answer: 29
Query Result: [(29,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Property_Location = 'calle del volto'



3
Question: What is the total number of properties found in "sopra la lista alla colonna"?
Answer: 23
Query Result: [(23,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Property_Location = 'sopra la lista alla colonna'



4
Question: How many properties are owned by owners with the first name "pier'alvise"?
Answer: 1
Query Result: [(1,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'pier''alvise'



4
Question: How many properties are owned by individuals with the first name "cecilia"?
Answer: 74
Query Result: [(74,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'cecilia'



4
Question: What is the count of properties owned by those with the given name "carlo"?
Answer: 155
Query Result: [(0,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'Carlo'



4
Question: How many properties are in possession of individuals named "michiel"?
Answer: 317
Query Result: Error: (psycopg2.errors.UndefinedFunction) function avg(text) does not exist
LINE 2: SELECT AVG(Rent_Income)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT AVG(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'michiel']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT AVG(Rent_Income)
FROM catastici
WHERE Owner_First_Name = 'michiel'



4
Question: What is the total number of properties owned by those with the first name "zuane"?
Answer: 119
Query Result: [(119,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_First_Name = 'zuane'



5
Question: How many properties are owned by owners with the last name "carli"?
Answer: 14
Query Result: [(14,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_Family_Name = 'carli'



5
Question: How many properties are owned by individuals with the last name "nani"?
Answer: 98
Query Result: Error: (psycopg2.errors.UndefinedFunction) function avg(text) does not exist
LINE 2: SELECT AVG(Rent_Income)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT AVG(Rent_Income)
FROM catastici
WHERE Rent_Income LIKE '%%ducats%%']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:

SELECT AVG(Rent_Income)
FROM catastici
WHERE Rent_Income LIKE '%ducats%'



5
Question: What is the count of properties owned by individuals with the surname "previani"?
Answer: 1
Query Result: [(1,)]
SQL:

SELECT COUNT(*)
FROM catastici
WHERE Owner_Family_Name = 'previani'



5

#### Wrong answers:
1. Fails to identify First and Family names correctly: e.g. `"pier alvise" "barbaro"`
2. When asked for number of unique owners, it is counting `DISTINCT Owner_First_Name` only -> solution could be to add another column with Owner ID
3. Converted `carlo` to `Carlo`

#### Errors:
1. Sum on `Rent_Income`:-> It is more dataset problem rather than generation problem
2. Sometimes when asked for `What kind of property`, it is returning `Rent_Income`

_**True: 40**; Errors: 9; Wrong Answers: 11_

## NSQL

In [83]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = "NumbersStation/nsql-llama-2-7B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name, 
    device_map = "auto", 
    torch_dtype = torch.float16
)

model.eval()

Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████| 3/3 [12:35<00:00, 251.93s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.14s/it]
/home/saydalie/.local/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/home/saydalie/.local/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:415: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/home/saydalie/.local/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/saydalie/.local/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:415: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096, padding_idx=2)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)

In [125]:
prompt = """You are asked a question about the people of Venice in 1740, who own properties.
All the information about the owner and the properties are given in the dataset.
The query will run on this database whose schema is represented in this string:
CREATE TABLE catastici
(
    Owner_First_Name VARCHAR(30), -- First name of the owner of the property
    Owner_Family_Name VARCHAR(30), -- Family name of the owner of the property
    Property_Type TEXT, -- Type of the property (e.g. casa, magazen, etc.)
    Rent_Income TEXT, -- Rent price of the property. It can be either a price in ducats, or the name of other good that is paid in exchange.
    Property_Location TEXT -- Ancient toponym of the property
)

-- Using valid PostgreSQL, answer the following questions for the table provided above.

-- {question}

SELECT"""

In [157]:
import sqlparse
import warnings
warnings.filterwarnings('ignore')

def generate_query(question, prompt=prompt, model=model, tokenizer=tokenizer, max_length=500):
    updated_prompt = prompt.format(question=question)
    inputs = tokenizer(updated_prompt, return_tensors="pt").to("cuda")
    generate_ids = model.generate(
        **inputs,
        max_length=max_length,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id
    )
    output = tokenizer.decode(generate_ids[0], skip_special_tokens = True)
    generated_sql = 'select '+sqlparse.format(output.split("SELECT")[-1].replace("'","''").replace('"',"'"), reindent=True).lower()
    return generated_sql

In [159]:
questions.iloc[1]['question']

'What is the surname of "alvise" for the proprietorship of "casa, per l\'altra metà" at "in fondamenta appresso il ponte di ca\' marcello"?'

In [162]:
query = '''How many properties are located in "corte del caparozolo"?'''
generated_sql = generate_query(question=query)
print(generated_sql)

select count(*)
from catastici
where property_location = 'corte del caparozolo'

In [163]:
from pprint import pprint
pprint(execute_query.invoke({"query":generated_sql}))

'[(7,)]'

### Test on Dataset

In [164]:
generated_sqls = []
generated_answers = []

for i,r in questions.iterrows():
    generated_sql = generate_query(r['question'])
    generated_sqls.append(generated_sql)
    generated_answer = execute_query.invoke({"query":generated_sql})
    generated_answers.append(generated_answer)

In [165]:
questions['generated_sql'] = generated_sqls
questions['generated_answer'] = generated_answers

In [166]:
questions

,level,category,question,answer,generated_sql,generated_answer
0,0,0,"What is the family name of ""chiara"" who owns ""...",stella,select owner_family_name\nfrom catastici\nwher...,
1,0,0,"What is the surname of ""alvise"" for the propri...",minoto,select owner_family_name\nfrom catastici\nwher...,
2,0,0,"What is the last name of ""zuanne"" who possesse...",loredan,select owner_family_name\nfrom catastici\nwher...,"[('loredan',), ('loredan',), ('loredan',), ('l..."
3,0,0,"Can you tell me the family name of ""zuanne"" fo...",corao,select owner_family_name\nfrom catastici\nwher...,
4,0,0,Who is the owner's last name with the first na...,fini,select owner_family_name\nfrom catastici\nwher...,"[('fini',)]"
5,0,1,"How much does ""zuane"" ""dona"" earn from their p...",35 ducati,select rent_income\nfrom catastici\nwhere prop...,"[('24 ducati',), ('35 ducati',), ('35 ducati',..."
6,0,1,"How much income does ""marc'antonio"" ""mocenigo""...",8 ducati,select rent_income\nfrom catastici\nwhere prop...,
7,0,1,"What is the rental revenue collected by ""piero...",128 ducati,select rent_income\nfrom catastici\nwhere owne...,Error: (psycopg2.errors.SyntaxError) syntax er...
8,0,1,"What is the earnings of ""domenico"" ""giovanelli...",12 ducati,select rent_income\nfrom catastici\nwhere prop...,
9,0,1,"What is the amount of ducats ""cristofolo"" ""ros...",40 ducati,select rent_income\nfrom catastici\nwhere prop...,"[('40 ducati',), ('30 ducati',)]"
10,0,2,"What type of property does ""fausto"" ""da pase"" ...",casa in soler,select property_type\nfrom catastici\nwhere ow...,Error: (psycopg2.errors.SyntaxError) syntax er...
11,0,2,"What type of property does ""daniela"" ""morosini...",casa,select property_type\nfrom catastici\nwhere ow...,Error: (psycopg2.errors.SyntaxError) syntax er...
12,0,2,"What category of real estate does ""anibal"" ""fo...",magazen,select property_type\nfrom catastici\nwhere ow...,Error: (psycopg2.errors.SyntaxError) syntax er...
13,0,2,"What kind of property is owned by ""piero"" ""fos...","casa, vuota",select property_type\nfrom catastici\nwhere ow...,Error: (psycopg2.errors.SyntaxError) syntax er...
14,0,2,"What is the property classification owned by ""...",casa a pepiano,select property_type\nfrom catastici\nwhere ow...,"[('casa in soler',), ('casa a pepiano',), ('ca..."
15,0,3,"Where is the property ""magazen da oglio"" of ""f...",corte tagliapietra,select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...
16,0,3,"Where is the ""casa"" owned by ""zacaria"" ""valier...",corte nova,select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...
17,0,3,"What is the location of ""alvise"" ""barbarigo""'s...",calle del isolotto sopra le scalle primo soler,select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...
18,0,3,Can you pinpoint the whereabouts of the proper...,calle di christi,select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...
19,0,3,"In which area is the property owned by ""marco""...",calle del spezier,select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...
20,0,4,"Who owns a property ""casetta"" in ""corte della ...",elisabetta palatina mora,select owner_family_name\nfrom catastici\nwher...,"[('mora',), ('mora',), ('mora',), ('mora',)]"
21,0,4,"Who is the proprietor of a ""casetta a pepian"" ...",regina contini,"select owner_first_name,\nowner_family_name\nf...","[('benetto', 'foscarini'), ('benetto', 'foscar..."
22,0,4,"Who owns the property type ""casa"" in ""calle de...",bortolo alberegno,"select owner_first_name,\nowner_family_name\nf...","[('bortolo', 'alberegno'), ('bortolo', 'albere..."
23,0,4,Can you identify the individual who possesses ...,polo renier ponte,"select owner_first_name,\nowner_family_name\nf...","[('polo', 'renier ponte')]"
24,0,4,What is the name of the owner with the family ...,zuanne sagredo,"select owner_first_name,\nowner_family_name\nf...","[('zuanne', 'sagredo'), ('paolina', 'badoer mo..."
25,1,0,"How many properties are owned by ""michiel"" ""mo...",126,select count(*)\nfrom catastici\nwhere owner_f...,Error: (psycopg2.errors.SyntaxError) syntax er...
26,1,0,"How many properties does ""maria"" ""zane venier""...",9,select count(*)\nfrom catastici\nwhere owner_f...,Error: (psycopg2.errors.SyntaxError) syntax er...
27,1,0,"What is the count of properties owned by ""dome...",2,select count(*)\nfrom catastici\nwhere owner_f...,Error: (psycopg2.errors.SyntaxError) syntax er...
28,1,0,How many properties are under the ownership of...,6,select count(*)\nfrom catastici\nwhere owner_f...,Error: (psycopg2.errors.SyntaxError) syntax er...
29,1,0,What is the total number of properties owned b...,2,select count(*)\nfrom catastici\nwhere owner_f...,Error: (psycopg2.errors.SyntaxError) syntax er...
30,1,1,How many different property types are there in...,3231,select count(distinct property_type)\nfrom cat...,"[(3231,)]"
31,1,1,How many distinct property types are present i...,3231,select count(distinct property_type)\nfrom cat...,"[(3231,)]"
32,1,1,What is the count of unique property types in ...,3231,select count(distinct property_type),Error: (psycopg2.errors.UndefinedColumn) colum...
33,1,1,How many different categories of properties ex...,3231,select count(distinct property_type),Error: (psycopg2.errors.UndefinedColumn) colum...
34,1,1,What is the total number of distinct property ...,3231,select count(distinct property_type),Error: (psycopg2.errors.UndefinedColumn) colum...
35,1,2,How many unique owners are there in the dataset?,6012,select count(distinct owner_first_name),Error: (psycopg2.errors.UndefinedColumn) colum...
36,1,2,How many unique owners are listed in the dataset?,6012,select count(distinct owner_first_name),Error: (psycopg2.errors.UndefinedColumn) colum...
37,1,2,What is the count of distinct owners in the da...,6012,select count(distinct owner_first_name),Error: (psycopg2.errors.UndefinedColumn) colum...
38,1,2,How many different owners are recorded in the ...,6012,select count(distinct owner_first_name),Error: (psycopg2.errors.UndefinedColumn) colum...
39,1,2,What is the total number of individual owners ...,6012,select count(distinct owner_first_name),Error: (psycopg2.errors.UndefinedColumn) colum...
40,1,3,"How many properties are located in ""corte del ...",7,select count(*)\nfrom catastici\nwhere propert...,"[(7,)]"
41,1,3,"How many properties are situated in ""corte del...",1,select count(*)\nfrom catastici\nwhere propert...,"[(1,)]"
42,1,3,"What is the count of properties located in ""co...",21,select count(*)\nfrom catastici\nwhere propert...,"[(21,)]"
43,1,3,"How many properties exist within ""calle del vo...",29,select count(*)\nfrom catastici\nwhere propert...,"[(29,)]"
44,1,3,What is the total number of properties found i...,23,select count(*)\nfrom catastici\nwhere propert...,"[(23,)]"
45,1,4,How many properties are owned by owners with t...,1,select count(*)\nfrom catastici\nwhere owner_f...,"[(1,)]"
46,1,4,How many properties are owned by individuals w...,74,select count(*)\nfrom catastici\nwhere owner_f...,"[(74,)]"
47,1,4,What is the count of properties owned by those...,155,select count(*)\nfrom catastici\nwhere owner_f...,"[(155,)]"
48,1,4,How many properties are in possession of indiv...,317,select count(*)\nfrom catastici\nwhere owner_f...,"[(317,)]"
49,1,4,What is the total number of properties owned b...,119,select count(*)\nfrom catastici\nwhere owner_f...,"[(119,)]"
50,1,5,How many properties are owned by owners with t...,14,select count(*)\nfrom catastici\nwhere owner_f...,"[(14,)]"
51,1,5,How many properties are owned by individuals w...,98,select count(*)\nfrom catastici\nwhere owner_f...,"[(98,)]"
52,1,5,What is the count of properties owned by indiv...,1,select count(*)\nfrom catastici\nwhere owner_f...,"[(1,)]"
53,1,5,How many properties are registered under indiv...,203,select count(*)\nfrom catastici\nwhere owner_f...,"[(203,)]"
54,1,5,What is the total number of properties held by...,126,select count(*)\nfrom catastici\nwhere owner_f...,"[(126,)]"
55,1,6,"What properties does ""zuanne"" ""bragadin"" own a...","['calle del forno', 'in corte dei vechii vicin...","select property_location,\nproperty_type\nfrom...",Error: (psycopg2.errors.SyntaxError) syntax er...
56,1,6,"Where are the properties owned by ""anzola"" ""ac...",['riva del vin'],select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...
57,1,6,"Can you list the locations where ""simon"" ""cont...","['calle dei bianchi', 'cale di ka tron', 'call...",select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...
58,1,6,"Which locations are properties owned by ""paolo...",['calle del spicier'],select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...
59,1,6,What are the locations of the properties owned...,"['fondamenta del bagatin', 'giù dal ponte baga...",select property_location\nfrom catastici\nwher...,Error: (psycopg2.errors.SyntaxError) syntax er...

### Evaluate

In [167]:
for _,row in questions.iterrows():
    print(row['category'])
    print(f"Question: {row['question']}")
    print(f"Answer: {row['answer']}")
    print(f"Query Result: {row['generated_answer']}")
    print('SQL:')
    print(row['generated_sql'])
    print('\n\n')

0
Question: What is the family name of "chiara" who owns "casa in 2 affittanze, porcion" in "corte nova"?
Answer: stella
Query Result:
SQL:
select owner_family_name
from catastici
where owner_first_name = 'chiara'
  and property_type = 'casa'
  and property_location = 'corte nova'



0
Question: What is the surname of "alvise" for the proprietorship of "casa, per l'altra metà" at "in fondamenta appresso il ponte di ca' marcello"?
Answer: minoto
Query Result:
SQL:
select owner_family_name
from catastici
where property_type = 'casa'
  and property_location = 'in fondamenta appresso il ponte di ca'' marcello'
  and rent_income = 'casa, per l''altra metà'
  and owner_first_name = 'alvise'



0
Question: What is the last name of "zuanne" who possesses "casa" at "calle de gobbi"?
Answer: loredan
Query Result: [('loredan',), ('loredan',), ('loredan',), ('loredan',), ('loredan',)]
SQL:
select owner_family_name
from catastici
where property_type = 'casa'
  and property_location = 'calle de gobbi'



0
Question: Can you tell me the family name of "zuanne" for the ownership of "bottegha da fruttarol serve per proprio uso" situated in "calle larga"?
Answer: corao
Query Result:
SQL:
select owner_family_name
from catastici
where property_type = 'casa'
  and property_location = 'calle larga'
  and rent_income = 'zuanne'



0
Question: Who is the owner's last name with the first name of "gerolamo" for the property type "casa" located at "calle di ca' boldù"?
Answer: fini
Query Result: [('fini',)]
SQL:
select owner_family_name
from catastici
where property_type = 'casa'
  and property_location = 'calle di ca'' boldù'
  and owner_first_name = 'gerolamo'



1
Question: How much does "zuane" "dona" earn from their property "casa" in "calle del sonzonio"?
Answer: 35 ducati
Query Result: [('24 ducati',), ('35 ducati',), ('35 ducati',), ('25 ducati',)]
SQL:
select rent_income
from catastici
where property_type = 'casa'
  and property_location = 'calle del sonzonio'



1
Question: How much income does "marc'antonio" "mocenigo" generate from the property labeled as "casa a pepian" in "calle de longhi"?
Answer: 8 ducati
Query Result:
SQL:
select rent_income
from catastici
where property_type = 'casa'
  and property_location = 'calle de longhi'



1
Question: What is the rental revenue collected by "piero" "giusti" from their "procuratia" in "seconda corte nella procuratia"?
Answer: 128 ducati
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'giusti'"
LINE 3: where owner_first_name = 'piero' 'giusti'
                                         ^

[SQL: select rent_income
from catastici
where owner_first_name = 'piero' 'giusti'
  and property_type = 'procuratia'
  and property_location = 'seconda corte nella procuratia']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select rent_income
from catastici
where owner_first_name = 'piero' 'giusti'
  and property_type = 'procuratia'
  and property_location = 'seconda corte nella procuratia'



1
Question: What is the earnings of "domenico" "giovanelli" from their property type "casa a pepiano" located in "corte della vida"?
Answer: 12 ducati
Query Result:
SQL:
select rent_income
from catastici
where property_type = 'casa'
  and property_location = 'corte della vita'



1
Question: What is the amount of ducats "cristofolo" "rossetti" makes annually from the "altro appartamento" in "calle dei botteri"?
Answer: 40 ducati
Query Result: [('40 ducati',), ('30 ducati',)]
SQL:
select rent_income
from catastici
where property_type = 'altro appartamento'
  and property_location = 'calle dei botteri'



2
Question: What type of property does "fausto" "da pase" own in "al ponticello della toletta"?
Answer: casa in soler
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'da pase'"
LINE 3: where owner_first_name = 'fausto' 'da pase'
                                          ^

[SQL: select property_type
from catastici
where owner_first_name = 'fausto' 'da pase'
  and property_location = 'al ponticello della tofetta']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_type
from catastici
where owner_first_name = 'fausto' 'da pase'
  and property_location = 'al ponticello della tofetta'



2
Question: What type of property does "daniela" "morosini" possess at "calle del magazen vechio"?
Answer: casa
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'morosini'"
LINE 3: where owner_first_name = 'daniela' 'morosini'
                                           ^

[SQL: select property_type
from catastici
where owner_first_name = 'daniela' 'morosini'
  and property_location = 'calle del magazen vechio']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_type
from catastici
where owner_first_name = 'daniela' 'morosini'
  and property_location = 'calle del magazen vechio'



2
Question: What category of real estate does "anibal" "fonte" own in "corte stella"?
Answer: magazen
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'fonte'"
LINE 3: where owner_first_name = 'anibal' 'fonte'
                                          ^

[SQL: select property_type
from catastici
where owner_first_name = 'anibal' 'fonte'
  and property_location = 'corte stella']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_type
from catastici
where owner_first_name = 'anibal' 'fonte'
  and property_location = 'corte stella'



2
Question: What kind of property is owned by "piero" "foscarini" at "sopra altra casa"?
Answer: casa, vuota
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'foscarini'"
LINE 3: where owner_first_name = 'piero' 'foscarini'
                                         ^

[SQL: select property_type
from catastici
where owner_first_name = 'piero' 'foscarini'
  and property_location = 'sopra altra casa']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_type
from catastici
where owner_first_name = 'piero' 'foscarini'
  and property_location = 'sopra altra casa'



2
Question: What is the property classification owned by "zuanne" "frascinetti" in "corte dell'anzolo"?
Answer: casa a pepiano
Query Result: [('casa in soler',), ('casa a pepiano',), ('casa a pepiano',)]
SQL:
select property_type
from catastici
where owner_family_name = 'frascinetti'
  and property_location = 'corte dell''anzolo'



3
Question: Where is the property "magazen da oglio" of "filippo" "pasqualigo" located?
Answer: corte tagliapietra
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'pasqualigo'"
LINE 3: where owner_first_name = 'filippo' 'pasqualigo'
                                           ^

[SQL: select property_location
from catastici
where owner_first_name = 'filippo' 'pasqualigo'
  and property_type = 'magazen' 'da oglio']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_location
from catastici
where owner_first_name = 'filippo' 'pasqualigo'
  and property_type = 'magazen' 'da oglio'



3
Question: Where is the "casa" owned by "zacaria" "valier" situated?
Answer: corte nova
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'valier'"
LINE 4:   and owner_family_name = 'zacaria' 'valier'
                                            ^

[SQL: select property_location
from catastici
where property_type = 'casa'
  and owner_family_name = 'zacaria' 'valier']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_location
from catastici
where property_type = 'casa'
  and owner_family_name = 'zacaria' 'valier'



3
Question: What is the location of "alvise" "barbarigo"'s "volta una"?
Answer: calle del isolotto sopra le scalle primo soler
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'barbarigo'"
LINE 3: where owner_family_name = 'alvise' 'barbarigo'
                                           ^

[SQL: select property_location
from catastici
where owner_family_name = 'alvise' 'barbarigo']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_location
from catastici
where owner_family_name = 'alvise' 'barbarigo'



3
Question: Can you pinpoint the whereabouts of the property owned by "pietro" "grimani luca" with the type of "bottegha da fenestrer"?
Answer: calle di christi
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'grimani luca'"
LINE 3: where owner_first_name = 'pietro' 'grimani luca'
                                          ^

[SQL: select property_location
from catastici
where owner_first_name = 'pietro' 'grimani luca'
  and property_type = 'bottegha da fenestrer']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_location
from catastici
where owner_first_name = 'pietro' 'grimani luca'
  and property_type = 'bottegha da fenestrer'



3
Question: In which area is the property owned by "marco" "dariva" found, categorized as "not given"?
Answer: calle del spezier
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'dariva'"
LINE 3: where owner_first_name = 'marco' 'dariva'
                                         ^

[SQL: select property_location
from catastici
where owner_first_name = 'marco' 'dariva']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select property_location
from catastici
where owner_first_name = 'marco' 'dariva'



4
Question: Who owns a property "casetta" in "corte della malvasia" with the family name of "mora"?
Answer: elisabetta palatina mora
Query Result: [('mora',), ('mora',), ('mora',), ('mora',)]
SQL:
select owner_family_name
from catastici
where property_type = 'casetta'
  and property_location = 'corte della malvasia'



4
Question: Who is the proprietor of a "casetta a pepian" in "corte busella" with the family name "contini"?
Answer: regina contini
Query Result: [('benetto', 'foscarini'), ('benetto', 'foscarini'), ('benetto', 'foscarini'), ('benetto', 'foscarini'), ('benetto', 'foscarini'), ('carlo', 'savioni'), ('regina', 'contini')]
SQL:
select owner_first_name,
owner_family_name
from catastici
where property_type = 'casetta a pepian'
  and property_location = 'corte busella'



4
Question: Who owns the property type "casa" in "calle del zadio" and bears the surname "alberegno"?
Answer: bortolo alberegno
Query Result: [('bortolo', 'alberegno'), ('bortolo', 'alberegno'), ('bortolo', 'alberegno'), ('ferdinando', 'salamon'), ('ferdinando', 'salamon'), ('giacomo', 'costanzi'), ('zuanne', 'foscari'), ('giovanni antonio', 'degna'), ('giovanni battista', 'bembo'), ('zuanne', 'fallier'), ('chiara', 'fallier bembo'), ('chiara', 'fallier bembo'), ('francesco', 'fallier'), ('barba', 'morosini'), ('chiara', 'fallier'), ('chiara', 'falier bembo'), ('bortolo', 'zanchi'), ('chiara', 'barbarigo michiel'), ("marc'antonio", 'michiel')]
SQL:
select owner_first_name,
owner_family_name
from catastici
where property_type = 'casa'
  and property_location = 'calle del zadio'



4
Question: Can you identify the individual who possesses a property categorized as "casa in solari con bottega da casseler" in "salizada" with the last name "renier ponte"?
Answer: polo renier ponte
Query Result: [('polo', 'renier ponte')]
SQL:
select owner_first_name,
owner_family_name
from catastici
where property_type = 'casa in solari con bottega da casseler'
  and property_location = 'salizada'



4
Question: What is the name of the owner with the family name "sagredo" for the property type "magazen" situated in "calle de favri"?
Answer: zuanne sagredo
Query Result: [('zuanne', 'sagredo'), ('paolina', 'badoer mocenigo')]
SQL:
select owner_first_name,
owner_family_name
from catastici
where property_type = 'magazen'
  and property_location = 'calle de favri'



0
Question: How many properties are owned by "michiel" "morosini"?
Answer: 126
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'morosini'"
LINE 3: where owner_first_name = 'michiel' 'morosini'
                                           ^

[SQL: select count(*)
from catastici
where owner_first_name = 'michiel' 'morosini']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(*)
from catastici
where owner_first_name = 'michiel' 'morosini'



0
Question: How many properties does "maria" "zane venier" own?
Answer: 9
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'zane venier'"
LINE 3: where owner_first_name = 'maria' 'zane venier'
                                         ^

[SQL: select count(*)
from catastici
where owner_first_name = 'maria' 'zane venier']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(*)
from catastici
where owner_first_name = 'maria' 'zane venier'



0
Question: What is the count of properties owned by "domenico" "aldi"?
Answer: 2
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'aldi'"
LINE 3: where owner_first_name = 'domenico' 'aldi'
                                            ^

[SQL: select count(*)
from catastici
where owner_first_name = 'domenico' 'aldi']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(*)
from catastici
where owner_first_name = 'domenico' 'aldi'



0
Question: How many properties are under the ownership of "pier alvise" "barbaro"?
Answer: 6
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'barbaro'"
LINE 3: where owner_first_name = 'pier alvise' 'barbaro'
                                               ^

[SQL: select count(*)
from catastici
where owner_first_name = 'pier alvise' 'barbaro']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(*)
from catastici
where owner_first_name = 'pier alvise' 'barbaro'



0
Question: What is the total number of properties owned by "fiama" "fiorelli"?
Answer: 2
Query Result: Error: (psycopg2.errors.SyntaxError) syntax error at or near "'fiorelli'"
LINE 3: where owner_first_name = 'fiama' 'fiorelli'
                                         ^

[SQL: select count(*)
from catastici
where owner_first_name = 'fiama' 'fiorelli']
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(*)
from catastici
where owner_first_name = 'fiama' 'fiorelli'



1
Question: How many different property types are there in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:
select count(distinct property_type)
from catastici



1
Question: How many distinct property types are present in the dataset?
Answer: 3231
Query Result: [(3231,)]
SQL:
select count(distinct property_type)
from catastici



1
Question: What is the count of unique property types in the dataset?
Answer: 3231
Query Result: Error: (psycopg2.errors.UndefinedColumn) column "property_type" does not exist
LINE 1: select count(distinct property_type)
                              ^

[SQL: select count(distinct property_type)]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(distinct property_type)



1
Question: How many different categories of properties exist in the dataset?
Answer: 3231
Query Result: Error: (psycopg2.errors.UndefinedColumn) column "property_type" does not exist
LINE 1: select count(distinct property_type)
                              ^

[SQL: select count(distinct property_type)]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(distinct property_type)



1
Question: What is the total number of distinct property types listed?
Answer: 3231
Query Result: Error: (psycopg2.errors.UndefinedColumn) column "property_type" does not exist
LINE 1: select count(distinct property_type)
                              ^

[SQL: select count(distinct property_type)]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(distinct property_type)



2
Question: How many unique owners are there in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedColumn) column "owner_first_name" does not exist
LINE 1: select count(distinct owner_first_name)
                              ^

[SQL: select count(distinct owner_first_name)]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(distinct owner_first_name)



2
Question: How many unique owners are listed in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedColumn) column "owner_first_name" does not exist
LINE 1: select count(distinct owner_first_name)
                              ^

[SQL: select count(distinct owner_first_name)]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(distinct owner_first_name)



2
Question: What is the count of distinct owners in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedColumn) column "owner_first_name" does not exist
LINE 1: select count(distinct owner_first_name)
                              ^

[SQL: select count(distinct owner_first_name)]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(distinct owner_first_name)



2
Question: How many different owners are recorded in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedColumn) column "owner_first_name" does not exist
LINE 1: select count(distinct owner_first_name)
                              ^

[SQL: select count(distinct owner_first_name)]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(distinct owner_first_name)



2
Question: What is the total number of individual owners represented in the dataset?
Answer: 6012
Query Result: Error: (psycopg2.errors.UndefinedColumn) column "owner_first_name" does not exist
LINE 1: select count(distinct owner_first_name)
                              ^

[SQL: select count(distinct owner_first_name)]
(Background on this error at: https://sqlalche.me/e/20/f405)
SQL:
select count(distinct owner_first_name)



3
Question: How many properties are located in "corte del caparozolo"?
Answer: 7
Query Result: [(7,)]
SQL:
select count(*)
from catastici
where property_location = 'corte del caparozolo'



3
Question: How many properties are situated in "corte delle candelle e in terren alli gesouiti"?
Answer: 1
Query Result: [(1,)]
SQL:
select count(*)
from catastici
where property_location = 'corte delle candelle e in terren alli gesouiti'



3
Question: What is the count of properties located in "corte del figher"?
Answer: 21
Query Result: [(21,)]
SQL:
select count(*)
from catastici
where property_location = 'corte del figher'



3
Question: How many properties exist within "calle del volto"?
Answer: 29
Query Result: [(29,)]
SQL:
select count(*)
from catastici
where property_location = 'calle del volto'



3
Question: What is the total number of properties found in "sopra la lista alla colonna"?
Answer: 23
Query Result: [(23,)]
SQL:
select count(*)
from catastici
where property_location = 'sopra la lista alla colonna'



4
Question: How many properties are owned by owners with the first name "pier'alvise"?
Answer: 1
Query Result: [(1,)]
SQL:
select count(*)
from catastici
where owner_first_name = 'pier''alvise'



4
Question: How many properties are owned by individuals with the first name "cecilia"?
Answer: 74
Query Result: [(74,)]
SQL:
select count(*)
from catastici
where owner_first_name = 'cecilia'



4
Question: What is the count of properties owned by those with the given name "carlo"?
Answer: 155
Query Result: [(155,)]
SQL:
select count(*)
from catastici
where owner_first_name = 'carlo'



4
Question: How many properties are in possession of individuals named "michiel"?
Answer: 317
Query Result: [(317,)]
SQL:
select count(*)
from catastici
where owner_first_name = 'michiel'



4
Question: What is the total number of properties owned by those with the first name "zuane"?
Answer: 119
Query Result: [(119,)]
SQL:
select count(*)
from catastici

#### Wrong answers:
1. Not setting all the filters asked in the question.
2. Cannot handle the apostrophe symbol `'`

#### Errors:
1. Problem with the lower/upper case
2. Cannot handle names with mulriple words

_**True: 24**; Errors: 28; Wrong Answers: 8_